name: github pages

on:
  push:
    branches:
      - source-hexo  # default branch


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clean
        uses: heowc/action-hexo@master
        with:
          args: clean
      - name: Generate
        uses: heowc/action-hexo@master
        with:
          args: generate
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
          publish_branch: master  # deploying branch
